# Consolidate the common configuration for reuse across multiple steps.
definitions:
  # Configure some default step values.
  step-defaults: &step-defaults
    timeout_in_minutes: 15
    retry:
      manual:
        permit_on_passed: true

  # Specify common agent queue parameters.
  queues:
    # Docker-based tasks should run in the Docker queue.
    docker-agents: &docker-agents
      agents:
        queue: "docker-builders"

  # Specify common plugin configurations.
  plugins:
    aws-sm: &aws-sm
      seek-oss/aws-sm#v2.3.1:
        file:
          - path: "./auth.json"
            secret-id: "buildkite/wordpress_composer_auth"
    ecr: &ecr
      ecr#v2.7.0:
        login: true
        no-include-email: true

  linting-conditional: &linting-conditional
    if: |
      (
        build.pull_request.base_branch == null
        && build.branch != 'live'
        && build.branch != 'main'
      )
      || (
        build.pull_request.base_branch != null
        && build.branch != 'main'
      )
  build-testing-conditional: &build-testing-conditional
    if: |
      (
        build.pull_request.base_branch == null
        && build.branch != 'live'
        && build.branch != 'main'
        && build.branch != 'integration'
      )
      || (
        build.pull_request.base_branch != null
        && build.branch != 'main'
      )
  build-release-conditional: &build-release-conditional
    if: |
      build.pull_request.base_branch == null
      && (
        build.branch == 'live'
        || build.branch == 'main'
        || build.branch == 'integration'
      )
  deployment-conditional: &deployment-conditional
    if: |
      build.branch == 'live'
      || build.branch == 'main'
      || build.branch == 'integration'

env:
  # Enable BuildKit engine.
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  COMPOSE_DOCKER_CLI_BUILD: 1

  # Dockerfile build stage target.
  DOCKERFILE_STAGE_TARGET: "pantheon"

  # Identify the address for the shared Buildkite ECR repository.
  IMAGE_REPOSITORY: "165761832703.dkr.ecr.us-east-1.amazonaws.com"

  # Define a common namespace for images to be published within the shared ECR repo.
  ECR_NAMESPACE: "${IMAGE_REPOSITORY}/buildkite"

  # Define service directory were the Dockerfile is used
  DOCKERFILE_LOCATION: "./"

  # Define the staring path for artifacts to be deployed from.
  ARTIFACTS_LOCATION: "./artifacts"

steps:
  - label: ":heavy_check_mark: :php: CodeSniffer Lint"
    key: "lint-phpcs"
    <<: *step-defaults
    <<: *docker-agents
    <<: *linting-conditional
    commands:
      - 'echo "--- :docker: Build PHP_CodeSniffer Linting Docker Image"'
      - "docker build --target php-linting -t ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-php-linting ${DOCKERFILE_LOCATION}"
      - 'echo "--- :docker: Run PHP_CodeSniffer Linting"'
      - "docker container run --rm ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-php-linting composer phpcs"
    plugins:
      # Pull the COMPOSER_AUTH from AWS Secrets Manager.
      - *aws-sm

  - label: ":heavy_check_mark: :php: Stan Lint"
    key: "lint-phpstan"
    <<: *step-defaults
    <<: *docker-agents
    <<: *linting-conditional
    commands:
      - 'echo "--- :docker: Build PHPStan Linting Image"'
      - "docker build --target php-linting -t ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-php-linting ${DOCKERFILE_LOCATION}"
      - 'echo "--- :docker: Run PHPStan Linting"'
      - "docker container run --rm ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-php-linting composer phpstan"
    plugins:
      # Pull the COMPOSER_AUTH from AWS Secrets Manager.
      - *aws-sm

  - label: ":heavy_check_mark: :eslint: Theme Linting"
    key: "lint-eslint"
    <<: *step-defaults
    <<: *docker-agents
    <<: *linting-conditional
    commands:
      - 'echo "--- :docker: Build Theme ESLint Linting Docker Image"'
      - "docker build --target theme-base -t ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-theme-linting ${DOCKERFILE_LOCATION}"
      - 'echo "--- :docker: Run Theme ESLint Linting"'
      - "docker container run --rm ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-theme-linting npm run eslint"
    plugins:
      # Pull the COMPOSER_AUTH from AWS Secrets Manager.
      - *aws-sm

  - label: ":heavy_check_mark: :stylelint: Theme Linting"
    key: "lint-stylelint"
    <<: *step-defaults
    <<: *docker-agents
    <<: *linting-conditional
    commands:
      - 'echo "--- :docker: Build Theme StyleLint Linting Docker Image"'
      - "docker build --target theme-base -t ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-theme-linting ${DOCKERFILE_LOCATION}"
      - 'echo "--- :docker: Run Theme StyleLint Linting"'
      - "docker container run --rm ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-theme-linting npm run stylelint"
    plugins:
      # Pull the COMPOSER_AUTH from AWS Secrets Manager.
      - *aws-sm

  - label: ":hammer: :docker: Build Test Image"
    key: "build-test"
    <<: *step-defaults
    <<: *docker-agents
    <<: *build-testing-conditional
    command:
      - "docker build --target ${DOCKERFILE_STAGE_TARGET} -t ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT} ${DOCKERFILE_LOCATION}"
    plugins:
      # Pull the COMPOSER_AUTH from AWS Secrets Manager.
      - *aws-sm

  - label: ":hammer: :docker: Build Release Image"
    key: "build-release"
    <<: *step-defaults
    <<: *docker-agents
    <<: *build-release-conditional
    command:
      - "docker build --target ${DOCKERFILE_STAGE_TARGET} -t ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT} ${DOCKERFILE_LOCATION}"
      - "docker push ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}"
    plugins:
      # Log into ECR for this build step to access and push images.
      - *ecr
      # Pull the COMPOSER_AUTH from AWS Secrets Manager.
      - *aws-sm

  - wait: ~

  - label: ":pipeline: Upload Deployment Pipeline"
    key: "deploy-pipeline"
    depends_on:
      - "build-release"
      - "lint-phpcs"
      - "lint-phpstan"
      - "lint-eslint"
      - "lint-stylelint"
    <<: *step-defaults
    <<: *deployment-conditional
    command: buildkite-agent pipeline upload .buildkite/pipeline.deploy.yml

