version: '3.6'
services:
  gesso:
    container_name: ddev-${DDEV_SITENAME}-gesso
    image: forumone/gesso:node-v18-php-8.1
    command: "sleep infinity"
    volumes:
      - ./../web/wp-content/themes/gesso:/var/www/html/web/wp-content/themes/gesso:cached
      - ".:/mnt/ddev_config"
    working_dir: /var/www/html/web/wp-content/themes/gesso
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    networks: [default, ddev_default]
