version: '3.6'
services:
  customblocks:
    container_name: ddev-${DDEV_SITENAME}-customblocks
    image: forumone/gesso:node-v18-php-8.1
    command: "sleep infinity"
    volumes:
      - ./../web/wp-content/plugins/custom-block-library:/var/www/html/web/wp-content/plugins/custom-block-library:cached
      - ".:/mnt/ddev_config"
    working_dir: /var/www/html/web/wp-content/plugins/custom-block-library
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    networks: [default, ddev_default]
